# Generated by Django 5.2.6 on 2025-09-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoNegado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidad_real', models.IntegerField()),
                ('cantidad_reservada', models.IntegerField()),
                ('producto_negado', models.IntegerField()),
                ('marca', models.CharField(max_length=100)),
                ('documento_origen', models.CharField(blank=True, max_length=100, null=True)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
