# Generated by Django 5.2.6 on 2025-09-30 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesamiento', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productonegado',
            old_name='documento_origen',
            new_name='origen',
        ),
        migrations.RemoveField(
            model_name='productonegado',
            name='cantidad_real',
        ),
        migrations.RemoveField(
            model_name='productonegado',
            name='cantidad_reservada',
        ),
        migrations.RemoveField(
            model_name='productonegado',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='productonegado',
            name='producto_negado',
        ),
        migrations.AddField(
            model_name='productonegado',
            name='cantidad_negada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productonegado',
            name='producto',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
