# Generated by Django 5.2.6 on 2025-09-30 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesamiento', '0002_rename_documento_origen_productonegado_origen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productonegado',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
