# Generated by Django 5.2.6 on 2025-10-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesamiento', '0003_alter_productonegado_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='pickingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreAsociado', models.CharField(max_length=50)),
                ('fechaFactura', models.DateField()),
                ('identificacionAsociado', models.CharField(max_length=15)),
                ('vendedor', models.CharField(max_length=50)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.CharField(max_length=50)),
                ('pesoUnitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cuidad', models.CharField(max_length=50)),
                ('codigoZona', models.CharField(max_length=50)),
                ('zona', models.CharField(max_length=50)),
                ('origen', models.CharField(max_length=7)),
                ('marca', models.CharField(max_length=50)),
                ('idOdoo', models.CharField(max_length=250)),
                ('fecha_procesamiento', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='productonegado',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='productonegado',
            name='origen',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='productonegado',
            name='producto',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='productonegado',
            name='referencia',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
