# Generated by Django 5.2.6 on 2025-10-10 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesamiento', '0004_pickingmodel_alter_productonegado_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickingmodel',
            name='producto',
            field=models.TextField(max_length=1000),
        ),
    ]
