# Generated by Django 5.2.6 on 2025-10-14 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesamiento', '0005_alter_pickingmodel_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickingmodel',
            name='vendedor',
            field=models.CharField(max_length=100),
        ),
    ]
