# Generated by Django 5.2.6 on 2025-11-12 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesamiento', '0006_alter_pickingmodel_vendedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='CortesLogistico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('nombre', models.TextField(max_length=200, unique=True)),
            ],
        ),
    ]
