# Generated by Django 5.2.6 on 2025-11-12 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesamiento', '0007_corteslogistico'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickingmodel',
            name='nombrecorte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='procesamiento.corteslogistico', to_field='nombre'),
        ),
    ]
