# Generated by Django 5.2.6 on 2025-11-12 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesamiento', '0008_pickingmodel_nombrecorte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickingmodel',
            name='nombrecorte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='procesamiento.corteslogistico'),
        ),
    ]
