# Generated by Django 5.2.6 on 2025-11-12 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesamiento', '0009_alter_pickingmodel_nombrecorte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickingmodel',
            name='nombreAsociado',
            field=models.CharField(max_length=500),
        ),
    ]
