# Generated by Django 5.2.6 on 2025-11-13 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_actividad', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('actividad', models.CharField(max_length=255, verbose_name='Actividad Realizada')),
                ('detalle', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Activo')),
            ],
            options={
                'verbose_name': 'Movimiento de Usuario',
                'ordering': ['-fecha_actividad'],
            },
        ),
    ]
